### ISSUE TITLE
Simplification isn't being deactivated when Simplification option = false

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStatsServices#24]
blue line is result:
![pasted image at 2016_11_22 09_07 am](https://cloud.githubusercontent.com/assets/8713714/20527800/f51f923e-b086-11e6-9aae-7355e435b592.png)

downloaded shapfile:
[SS_CT20161122064800520000.zip](https://github.com/USGS-WiM/StreamStatsServices/files/606673/SS_CT20161122064800520000.zip)
[SS_CT20161122064725253000.zip](https://github.com/USGS-WiM/StreamStatsServices/files/606674/SS_CT20161122064725253000.zip)

**Comment by HansVraga** [comment]
Simplification is implemented client-side now.
