### ISSUE TITLE
stormwater.py changed

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStatsServices#41]
[Stormwater.py.txt](https://github.com/USGS-WiM/StreamStatsServices/files/2998423/Stormwater.py.txt)

strmdrnoption = "direct surface contribution only" if directSurfaceContributionOnly else "full delineation"
            #direct surface contribution only, full delineation, simulated inlet location
            result=netTrace.GetWatershedViaNetTrace(PourPoint,2,fdr.Dataset, strlnk,strlnk,
                                                               cat, adjCat, sink, pipe, strm, hydrJct,
                                                               strmdrnoption, 
                                                               os.path.join(featurePath,datasetName["basin"]),
                                                               os.path.join(featurePath,datasetName["point"]),
                                                               os.path.join(featurePath,datasetName["swda"]))

**Comment by HansVraga** [comment]
@jknewson was this part of your stormwater work? Can this be closed?

**Comment by amedenblik** [comment]
This change is now in the jknstormwaterCore and kjstormwater_mrb branches.
